const PROJECTS = [
  {
    "id": "p0",
    "name": "Jasmin",
    "area": "Rawang",
    "type": "Landed",
    "price": "RM 808k+",
    "tenure": "Freehold",
    "title": "Strata",
    "landArea": "22×70",
    "builtUp": "1,871 sqft",
    "beds": "4",
    "baths": "4",
    "developer": "BRDB2",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Jasmin | RM 808k+ | Freehold | Strata | 22×70 | 1,871 sqft | 4 | 4 | BRDB2"
  },
  {
    "id": "p1",
    "name": "Murraya",
    "area": "Rawang",
    "type": "Landed",
    "price": "839k+",
    "tenure": "Freehold",
    "title": "Strata",
    "landArea": "20×70",
    "builtUp": "1,826 sqft",
    "beds": "4",
    "baths": "3",
    "developer": "BRDB",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Murraya | 839k+ | Freehold | Strata | 20×70 | 1,826 sqft | 4 | 3 | BRDB"
  },
  {
    "id": "p2",
    "name": "M Panora",
    "area": "Rawang",
    "type": "Landed",
    "price": "RM 661k+",
    "tenure": "Freehold",
    "title": "Strata",
    "landArea": "24×65",
    "builtUp": "1,770 sqft",
    "beds": "4",
    "baths": "3",
    "developer": "Mah Sing",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: M Panora | RM 661k+ | Freehold | Strata | 24×65 | 1,770 sqft | 4 | 3 | Mah Sing"
  },
  {
    "id": "p3",
    "name": "TR1",
    "area": "Rawang",
    "type": "Landed",
    "price": "RM 695k+",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "22×70",
    "builtUp": "1,672 sqft",
    "beds": "4",
    "baths": "3",
    "developer": "Hong Bee Land",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: TR1 | RM 695k+ | Freehold | Individual | 22×70 | 1,672 sqft | 4 | 3 | Hong Bee Land"
  },
  {
    "id": "p4",
    "name": "TR 2",
    "area": "Rawang",
    "type": "Landed",
    "price": "RM 749k+",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "22×70",
    "builtUp": "1,783 sqft",
    "beds": "4",
    "baths": "4",
    "developer": "Hong Bee Land",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: TR 2 | RM 749k+ | Freehold | Individual | 22×70 | 1,783 sqft | 4 | 4 | Hong Bee Land"
  },
  {
    "id": "p5",
    "name": "Blooming",
    "area": "Rawang",
    "type": "Landed",
    "price": "RM 719k+",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "20×70",
    "builtUp": "1,786 sqft",
    "beds": "4",
    "baths": "3",
    "developer": "Guocoland",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Blooming | RM 719k+ | Freehold | Individual | 20×70 | 1,786 sqft | 4 | 3 | Guocoland"
  },
  {
    "id": "p6",
    "name": "Sari Alamanda 4",
    "area": "Rawang",
    "type": "Landed",
    "price": "RM 511k+",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "20×60/65/70",
    "builtUp": "1,672 sqft",
    "beds": "4",
    "baths": "3",
    "developer": "Amalan Setar",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Sari Alamanda 4 | RM 511k+ | Freehold | Individual | 20×60/65/70 | 1,672 sqft | 4 | 3 | Amalan Setar"
  },
  {
    "id": "p7",
    "name": "M Aruna",
    "area": "Rawang",
    "type": "Landed",
    "price": "—",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "22×75 Corner",
    "builtUp": "2,271 sqft",
    "beds": "4",
    "baths": "3",
    "developer": "Mah Sing",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: M Aruna | — | Freehold | Individual | 22×75 Corner | 2,271 sqft | 4 | 3 | Mah Sing"
  },
  {
    "id": "p8",
    "name": "Amaryllis",
    "area": "Rawang",
    "type": "Landed",
    "price": "RM 1.016m+",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "24×70",
    "builtUp": "3,114 sqft",
    "beds": "3+1",
    "baths": "3+1",
    "developer": "BRDB",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Amaryllis | RM 1.016m+ | Freehold | Individual | 24×70 | 3,114 sqft | 3+1 | 3+1 | BRDB"
  },
  {
    "id": "p9",
    "name": "Anggun 3",
    "area": "Rawang",
    "type": "Landed",
    "price": "RM 883k / RM1.8m",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "22×70 / 40×80",
    "builtUp": "3,315 / 3,360 sqft",
    "beds": "5 / 4+1",
    "baths": "5",
    "developer": "Hong Bee Land",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Anggun 3 | RM 883k / RM1.8m | Freehold | Individual | 22×70 / 40×80 | 3,315 / 3,360 sqft | 5 / 4+1 | 5 | Hong Bee Land"
  },
  {
    "id": "p10",
    "name": "The Rise2 Emerald",
    "area": "Rawang",
    "type": "Landed",
    "price": "RM 1.78m+",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "49×88 / 87×84",
    "builtUp": "2,987 / 3,837 sqft",
    "beds": "5 / 6+1",
    "baths": "6 / 7+1",
    "developer": "Guocoland Berhad",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: The Rise2 Emerald | RM 1.78m+ | Freehold | Individual | 49×88 / 87×84 | 2,987 / 3,837 sqft | 5 / 6+1 | 6 / 7+1 | Guocoland Berhad"
  },
  {
    "id": "p11",
    "name": "Botanica Hills",
    "area": "Rawang",
    "type": "Landed",
    "price": "RM 567k+",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "20×60 / 22×60",
    "builtUp": "1,660 sqft",
    "beds": "4",
    "baths": "3",
    "developer": "Chin Hin / Stellar Trinity",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Botanica Hills | RM 567k+ | Freehold | Individual | 20×60 / 22×60 | 1,660 sqft | 4 | 3 | Chin Hin / Stellar Trinity"
  },
  {
    "id": "p12",
    "name": "Caledonia (Ayana)",
    "area": "Gamuda Gardens / Kundang",
    "type": "Landed",
    "price": "RM 484,310 / RM583,110",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "20×65 / 22×70",
    "builtUp": "1,572 / 1,990 sqft",
    "beds": "4",
    "baths": "3",
    "developer": "KLK Land",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Caledonia (Ayana) | RM 484,310 / RM583,110 | Freehold | Individual | 20×65 / 22×70 | 1,572 / 1,990 sqft | 4 | 3 | KLK Land"
  },
  {
    "id": "p13",
    "name": "Quinton",
    "area": "Gamuda Gardens / Kundang",
    "type": "Landed",
    "price": "RM 1.09m+",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "32×65",
    "builtUp": "2,016 sqft",
    "beds": "4",
    "baths": "4",
    "developer": "KLK Land",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Quinton | RM 1.09m+ | Freehold | Individual | 32×65 | 2,016 sqft | 4 | 4 | KLK Land"
  },
  {
    "id": "p14",
    "name": "Gamuda Gardens Park Astor",
    "area": "Gamuda Gardens / Kundang",
    "type": "Landed",
    "price": "RM 713k+",
    "tenure": "Freehold",
    "title": "Individual",
    "landArea": "20×60/65/75",
    "builtUp": "1,557 sqft",
    "beds": "4",
    "baths": "3",
    "developer": "Gamuda Land",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Gamuda Gardens Park Astor | RM 713k+ | Freehold | Individual | 20×60/65/75 | 1,557 sqft | 4 | 3 | Gamuda Land"
  },
  {
    "id": "p15",
    "name": "Gamuda Heston Hill",
    "area": "Gamuda Gardens / Kundang",
    "type": "Landed",
    "price": "RM 1.06m+",
    "tenure": "Leasehold",
    "title": "Strata",
    "landArea": "22/26/35×70 · 45×80/100",
    "builtUp": "2,331 / 5,617 sqft",
    "beds": "4 / 5+2",
    "baths": "4–7",
    "developer": "Gamuda Land",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Gamuda Heston Hill | RM 1.06m+ | Leasehold | Strata | 22/26/35×70 · 45×80/100 | 2,331 / 5,617 sqft | 4 / 5+2 | 4–7 | Gamuda Land"
  },
  {
    "id": "p16",
    "name": "Gamuda Valeria",
    "area": "Gamuda Gardens / Kundang",
    "type": "Landed",
    "price": "RM 1.03m+",
    "tenure": "Leasehold",
    "title": "Strata",
    "landArea": "22/24/26/28/35×75/85/80/70",
    "builtUp": "2,353 / 3,189 sqft",
    "beds": "4",
    "baths": "4",
    "developer": "Gamuda Land",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Gamuda Valeria | RM 1.03m+ | Leasehold | Strata | 22/24/26/28/35×75/85/80/70 | 2,353 / 3,189 sqft | 4 | 4 | Gamuda Land"
  },
  {
    "id": "p17",
    "name": "Monarc Semi-D",
    "area": "Gamuda Gardens / Kundang",
    "type": "Semi-D",
    "price": "RM 1.95m+",
    "tenure": "—",
    "title": "—",
    "landArea": "36 / 40×80",
    "builtUp": "2,812 sqft",
    "beds": "4",
    "baths": "5",
    "developer": "—",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Monarc Semi-D | RM 1.95m+ | — | — | 36 / 40×80 | 2,812 sqft | 4 | 5 | —"
  },
  {
    "id": "p18",
    "name": "Monarc Bungalow",
    "area": "Gamuda Gardens / Kundang",
    "type": "Bungalow",
    "price": "RM 4.42m+",
    "tenure": "—",
    "title": "—",
    "landArea": "60×120",
    "builtUp": "6,047 sqft",
    "beds": "5",
    "baths": "6",
    "developer": "—",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Monarc Bungalow | RM 4.42m+ | — | — | 60×120 | 6,047 sqft | 5 | 6 | —"
  },
  {
    "id": "p19",
    "name": "Gamuda Illaria",
    "area": "Gamuda Gardens / Kundang",
    "type": "Landed",
    "price": "RM 568k+ / RM733k+",
    "tenure": "—",
    "title": "—",
    "landArea": "18×65 / 20×65 / 22×70",
    "builtUp": "1,202 / 1,788 / 2,026 sqft",
    "beds": "3 / 4",
    "baths": "3",
    "developer": "—",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600573472550-8090b5e0745e?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Gamuda Illaria | RM 568k+ / RM733k+ | — | — | 18×65 / 20×65 / 22×70 | 1,202 / 1,788 / 2,026 sqft | 3 / 4 | 3 | —"
  },
  {
    "id": "p20",
    "name": "Joya",
    "area": "Gamuda Gardens / Kundang",
    "type": "Landed",
    "price": "RM 913k+",
    "tenure": "—",
    "title": "—",
    "landArea": "24×65 / 75",
    "builtUp": "2,288 sqft",
    "beds": "4",
    "baths": "4",
    "developer": "—",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Joya | RM 913k+ | — | — | 24×65 / 75 | 2,288 sqft | 4 | 4 | —"
  },
  {
    "id": "p21",
    "name": "Kundang Estate",
    "area": "Gamuda Gardens / Kundang",
    "type": "Landed",
    "price": "RM 730k+",
    "tenure": "Leasehold",
    "title": "Individual",
    "landArea": "20×70 / 24×70",
    "builtUp": "2,009 sqft",
    "beds": "4",
    "baths": "3 or 4",
    "developer": "Gamuda Land",
    "units": "See workbook",
    "completion": "See workbook",
    "landSize": "See workbook",
    "mall": "See workbook",
    "toll": "See workbook",
    "image": "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80",
    "sourceData": "Workbook summary: Kundang Estate | RM 730k+ | Leasehold | Individual | 20×70 / 24×70 | 2,009 sqft | 4 | 3 or 4 | Gamuda Land"
  }
];